# Generated by Django 3.1.7 on 2021-03-18 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table='Students',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
